### ISSUE TITLE
Plugins cause the frontend to crash if not logged in

### ISSUE THREAD

**Issue by theCrius** [chapoi/discourse-silenced-flair#1]
Classic case of assumption that the user is logged in I believe. Happened to me as well when working on mine :)

When not logged in, discourse never load anything and this error appear in console:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'moderator')
    at discourse-silenced-flair-38d3612e98a8a73131e47f7907c58ee597cabbf106fdfd352f2ddd362bc661cf.js:10:58
    at e.withPluginApi (discourse-d43116e947daa5c7445a0a3cabbddf8d07b956fdce99f9b02bc9124f218e74ff.js:5659:13)
    at Object.initialize (discourse-silenced-flair-38d3612e98a8a73131e47f7907c58ee597cabbf106fdfd352f2ddd362bc661cf.js:9:72)
    at i.initialize (discourse-d43116e947daa5c7445a0a3cabbddf8d07b956fdce99f9b02bc9124f218e74ff.js:72:38)
    at vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:2379:679
    at e.each (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:3894:1)
    at e.walk (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:3884:30)
    at e.each (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:3876:157)
    at e.topsort (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:3876:203)
    at e._runInitializer (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:2382:3)
    at e.runInstanceInitializers (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:2379:629)
    at e._bootSync (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:2236:448)
    at e.didBecomeReady (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:2256:89)
    at p.invoke (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:4335:182)
    at p.flush (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:4327:141)
    at h.flush (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:4342:207)
    at q._end (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:4406:9)
    at _boundAutorunEnd (vendor-e85be2e7f80b544c53cefff39c43ff0346cb45be4ed155cb9f7547dd97135bf8.js:4354:595)
```

`moderator` is an attribute of the logged in user object. It should suffice to add a check before that, which assure that the user object exists.

**Comment by theCrius** [comment]
Pull request created, feel free to edit whatever you think it needs editing 👍
